name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Substitua pela versão desejada

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Certifique-se de ter um arquivo requirements.txt

    - name: Run Tests
      run: |
        pytest  # Execute seus testes com pytest (ou outra ferramenta de teste)

    - name: Package Application
      run: |
        python setup.py sdist bdist_wheel  # Empacota a aplicação, se necessário
